name: 'Push'
description: 'Simple git push with private key'
inputs:
  username:
    description: 'Repo username'
    required: true
  host:
    description: 'Repo host'
    required: true
  path:
    description: 'Repo path'
    required: true
  private_key:
    description: 'Repo private key'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.username }}
    - ${{ inputs.host }}
    - ${{ inputs.path }}
    - ${{ inputs.private_key }}
