name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  username:
    description: 'Repo username'
    required: true
  host:
    description: 'Repo host'
    required: true
  path:
    description: 'Repo path'
    required: true
  key:
    description: 'Repo key'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.username }}
    - ${{ inputs.host }}
    - ${{ inputs.path }}
    - ${{ inputs.key }}
